### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by rauerhans** [cyubachi/gcp-container-batch#1]
does this still work, might be useful for me. Just seeing that you haven't worked on it for a while.

**Comment by cyubachi** [comment]
Yes, it still works.
But I think it is better to use [GCP batch](https://cloud.google.com/blog/products/compute/new-batch-service-processes-batch-jobs-on-google-cloud?hl=en) than to use this, because it is better managed.

**Comment by rauerhans** [comment]
thanks mate, I figured, actually I plan to use vertex pipelines now
